### ISSUE TITLE
CUDA & cudnn

### ISSUE THREAD

**Issue by fusionlove** [imatge-upc/saliency-salgan-2017#10]
Hello, thank you for making your code available. I'm having some issues with cudnn (not able to obtain a cudnn handle when running the predict script).

Could you provide some more details about which version of CUDA and cudnn you are using?
Thanks
Fintan
Attention lab, UCL

**Comment by fusionlove** [comment]
If anyone else is having this issue, the code appears to work OK without cudnn, if you disable it by modifying the theano flags.

**Comment by junting** [comment]
Hi @fusionlove ,

The version of CUDA is 7.5 and CuDNN is v5.0.
Best,

Junting

**Comment by fusionlove** [comment]
Thanks for your speedy response!
F

**Comment by shanwei0949** [comment]
Hi,@fusionlove,
 I have the same problem in the process of training, can you tell me how to solve this problem?
Thanks a lot.

Best,
Wei Shan
