### ISSUE TITLE
Load Binary Images instead of matfiles in dataRepresentation.py

### ISSUE THREAD

**Issue by saeedizadi** [imatge-upc/saliency-salgan-2017#11]
Hello,
I am going to load my own binary masks as the ground truths in the _01-data_preprocessing.py_ file. Should I normalize the image values in the range of [0,1] manually or the code works based on [0-255] values?

Thanks

**Comment by junting** [comment]
Hello @saeedizadi ,

The code works with image within the range of [0,255] .

Best,
Junting
