### ISSUE TITLE
what is the data format for running the Salgan

### ISSUE THREAD

**Issue by endeavorui** [imatge-upc/saliency-salgan-2017#16]
sorry to interrupt again.
I am still struggle to parse the json file from SALICON dataset into the format required to run salgan. Would you please specify the parsing methods? or please clarify what is saliency map and fixations? My best guess is saliency map equals to annotations and the fixations are coordinates of the dots. If yes, what is the data structure of fixations?

Since the salgan used the 'mat' file, please help to confirm it.

**Comment by endeavorui** [comment]
In addition, the fixations for one image comes from multiple workers. Should I choose either one or combine them all?

**Comment by junting** [comment]
Hi @endeavorui, 

Fixations maps are build based on fixation annotations of all workers.  Saliency map is just a continuous map and is obtained by blurring the fixation map with a gaussian filter.

We were using the '.mat' file, the fixation maps were stored in this format. 

Best,
Junting

**Comment by endeavorui** [comment]
Is it possible to share with some samples of saliency maps and fixations?

**Comment by junting** [comment]
Hi @endeavorui ,

You can find some examples here.[http://saliency.mit.edu/exampleImgs/banner.001.png](url)
