### ISSUE TITLE
Wrong link to requirements.txt

### ISSUE THREAD

**Issue by Tobias-Fischer** [imatge-upc/saliency-salgan-2017#18]
Hi,
It seems like the link to `requirements.txt` is wrong. Currently, it is `https://github.com/imatge-upc/saliency-salgan-2017/blob/junting/requirements.txt`, but I think it should be `https://raw.githubusercontent.com/imatge-upc/saliency-salgan-2017/master/requirements.txt`. (2 issues: `junting` vs `master` branch and `raw.` vs non `raw.`.

Best, Tobias

**Comment by junting** [comment]
Ok! Thanks for your comment! It is changed now!
