### ISSUE TITLE
looking for modelWeights0080.npz

### ISSUE THREAD

**Issue by josephwinston** [imatge-upc/saliency-salgan-2017#2]
I'm running the test script to produce the saliency maps as shown in the README (```python 03-predict.py```)

I cannot find in the instructions where to obtain the model weights.   I see <https://imatge.upc.edu/web/sites/default/files/resources/1720/saliency/2017-salgan/gen_modelWeights0090.npz> and <https://imatge.upc.edu/web/sites/default/files/resources/1720/saliency/2017-salgan/discrim_modelWeights0090.npz> but the prefix of either ```gen_``` or ```discrim_``` is not present in the call to ```load_weights``` in ```03-predict``` nor the epic of 80.

**Comment by junting** [comment]
Hello @josephwinston,

Thank you for your interest! I found some bug in the code, and it is fixed now! 
PS: The prefix of `gen_` or  `discrim_` can be set with the input argument `path`
`load_weights(model.net['output'], path='gen_', epochtoload=90)`
But anyway, there are some other minor bugs too, so please update the code with the latest changes and you can try to run the test script with the provided test image to compare the result.

Best,
Junting
