### ISSUE TITLE
Pre-trained Network Parameters

### ISSUE THREAD

**Issue by fwahhab89** [imatge-upc/saliency-salgan-2017#20]
I am doing some experiments on the SALGAN. I noticed that the results reported in the arXiv say that the training is done using 256x192 size images and saliency maps but the code has default values of 320x240. My question is that in the paper you performed training on 256x192 images, which would change the aspect ratio of the SALICON dataset. Isn't that a problem ??

**Comment by junting** [comment]
Hi @fwahhab89,

The image is smaller in size but the aspect ratio is not changed.

Best,
Junting
