### ISSUE TITLE
Access Forbidden in model links

### ISSUE THREAD

**Issue by maups** [imatge-upc/saliency-salgan-2017#21]
When I try to download the models (generator/discriminator), I receive the following Access Forbidden error:

Access Forbidden
Error Type: 403

Access to the URL that you requested is forbidden.

If you think that this is an error, please send us an email: admin.imatge@upc.edu. We will do all we can to fix it as soon as possible.

<< Go back to previous page.

**Comment by agilmor** [comment]
Links are fixed now.
Sorry for the inconveniences.
