### ISSUE TITLE
paper code environment configuration and operation requirements

### ISSUE THREAD

**Issue by zhuzhuzhuxin** [imatge-upc/saliency-salgan-2017#23]
Hello!I am a new student of computer science and technology.When I run the code ,I encountered some problems: the operating environment configuration is not successful (I follow the prompt step by step to install the required software, or not), It makes me really confused.I want to ask about more details of the paper code environment configuration and operation requirements.If anyone can help me,I will be very grateful.Thanks!
                                                                                                          Xin Zhu

**Comment by junting** [comment]
Hello @zhuzhuzhuxin ,

I recommend you to create your own virtual environment and use the provided requirement file to install all dependencies

`pip install -r https://raw.githubusercontent.com/imatge-upc/saliency-salgan-2017/master/requirements.txt`

Best,

**Comment by zhuzhuzhuxin** [comment]
@junting Thank you very much.
