### ISSUE TITLE
Visualize predicted Scan-paths on input image

### ISSUE THREAD

**Issue by nileshpd1211** [imatge-upc/saliency-salgan-2017#34]
Hi,
I'm new to both python as well as deep learning environment. I successfully implemented the code by giving an image as an input and saving the predicted scan-path output as a .mat file. Can someone kindly help me with how to visualize the scan-path over the input image? 

Thanks a lot :D

**Comment by xavigiro** [comment]
SalGAN does not generate scanpaths, but saliency maps. In case you would like scanpaths, you may be interested in our other work [SaltiNet](https://massens.github.io/saliency-360salient-2017/).
