### ISSUE TITLE
Requirements (Lasagne, optpy)

### ISSUE THREAD

**Issue by njss** [imatge-upc/saliency-salgan-2017#6]
when installing the requirements it is not possible to find:
Lasagne==0.2.dev1 and others...

Where is this version of Lasagne? the latest release is 0.1
also the same for optpy...

**Comment by junting** [comment]
Hello @njss ,

You can install the lates version of Lasagne and Theano using these commands:
`pip install --upgrade https://github.com/Theano/Theano/archive/master.zip`
`pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip`

The optpy is not needed for training or testing, I will remove it from requirements.txt

Best,
Junting

**Comment by aligholami** [comment]
Unfortunately you forgot to remove it!
