### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by casperkaae** [imatge-upc/saliency-salgan-2017#8]
Hi

Your SalGAN approach looks super interesting!

Do you provide a pretrained model? Might just be me who can't find the link :)

Best
Casper

**Comment by xavigiro** [comment]
Hi Casper,

thanks for you kind words.

I am not sure what you mean by "pretrained" model, but we do provide the models we trained, both generator on discriminator. You can find them on the "Models" section of our [website](https://imatge-upc.github.io/saliency-salgan-2017/) or [README.md](https://github.com/imatge-upc/saliency-salgan-2017/blob/master/README.md).

Does this answer your question ?

If so, please close the issue.

Thanks !

**Comment by casperkaae** [comment]
Hi again

Well, guess i should learn to use my eyes better :)

Thanks a lot!
